CREATE TABLE accounts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url TEXT NOT NULL,
    email_used TEXT,
    user_name TEXT,
    password TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id)
);